[connections.supabase]
dialect = "postgresql"
host = "aws-0-eu-west-1.pooler.supabase.com"
port = 5432
database = "postgres"
username = "postgres.ioxzwwaonwvmupjkilbx"
password = "hu3B@2052-eVa"
SUPABASE_URL = "https://ioxzwwaonwvmupjkilbx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveHp3d2Fvbnd2bXVwamtpbGJ4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NDY4OTcyMiwiZXhwIjoyMTAwMjY1NzIyfQ.AVhMYVTWlUtnsEXcnEOxYc20hZTf0RUI1Z_R-TXBJ0w"  